# Generated by Django 3.1.1 on 2020-09-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='price')),
                ('production_date', models.DateField(auto_now_add=True, verbose_name='production_date')),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='power')),
                ('productivity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='productivity')),
                ('preview_qty', models.PositiveIntegerField(verbose_name='preview_qty')),
                ('image', models.ImageField(upload_to='goods')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='good.category')),
                ('good', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdm.product')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товар',
                'ordering': ['good'],
            },
        ),
    ]
