# Generated by Django 3.1.1 on 2020-09-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['name'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товар'},
        ),
    ]
