# Generated by Django 3.1.1 on 2020-09-22 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20200921_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='production_date',
        ),
        migrations.AddField(
            model_name='good',
            name='sale_end',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='sale_end'),
        ),
        migrations.AddField(
            model_name='good',
            name='sale_start',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='sale_start'),
        ),
        migrations.AlterField(
            model_name='good',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='power'),
        ),
        migrations.AlterField(
            model_name='good',
            name='preview_qty',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='preview_qty'),
        ),
        migrations.AlterField(
            model_name='good',
            name='productivity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='productivity'),
        ),
    ]
