# Generated by Django 3.1.1 on 2020-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_auto_20200922_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, upload_to='goods'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sale_end',
            field=models.DateField(blank=True, null=True, verbose_name='sale_end'),
        ),
    ]
