# Generated by Django 3.1.1 on 2020-10-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0004_auto_20200922_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/good/images'),
        ),
    ]
