# Generated by Django 3.1.1 on 2020-09-20 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('property_form', models.CharField(blank=True, max_length=10, verbose_name='property_form')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.URLField(blank=True)),
                ('adress', models.CharField(blank=True, max_length=50, verbose_name='adress')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='phone')),
                ('viber', models.CharField(blank=True, max_length=15, verbose_name='viber')),
                ('f_name', models.CharField(blank=True, max_length=15, verbose_name='f_name')),
                ('m_name', models.CharField(blank=True, max_length=15, verbose_name='m_name')),
                ('l_name', models.CharField(blank=True, max_length=15, verbose_name='l_name')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='position')),
                ('language', models.CharField(choices=[('ru', 'русский'), ('ua', 'украинский'), ('pl', 'польский'), ('en', 'английский')], default='ru', max_length=2, verbose_name='language')),
                ('last_visit', models.DateField(default=datetime.date.today, verbose_name='last_visit')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.SmallIntegerField(choices=[(0, 'Готовая продукция'), (1, 'Комплексы'), (2, 'Сборочные единицы'), (3, 'Детали'), (4, 'Стандартные изделия'), (5, 'Прочие изделия'), (6, 'Материалы'), (7, 'Комплекты')], default=3)),
                ('part_number', models.CharField(max_length=50, null=True, unique=True, verbose_name='part_number')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='note')),
                ('mass', models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='mass')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='cost')),
                ('cooperation', models.BooleanField(default=False, verbose_name='cooperation')),
                ('drawing', models.FileField(upload_to='drawings')),
                ('cam_file', models.FileField(upload_to='cam_files')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdm.counterparty')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdm.group')),
            ],
            options={
                'verbose_name': 'ТМЦ',
                'verbose_name_plural': 'ТМЦ',
                'ordering': ['partition', 'part_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=30, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='pdm.product')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder', to='pdm.product')),
            ],
            options={
                'verbose_name': 'Спецификация (производство)',
                'verbose_name_plural': 'Спецификации (производство)',
                'ordering': ['owner', 'member'],
            },
        ),
        migrations.CreateModel(
            name='ProductProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(blank=True, decimal_places=3, max_digits=8, verbose_name='area')),
                ('coating', models.CharField(blank=True, max_length=100, verbose_name='coating')),
                ('treatment', models.CharField(blank=True, max_length=15, verbose_name='treatment')),
                ('stocksize', models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='stocksize')),
                ('perimeter', models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='perimeter')),
                ('incut', models.SmallIntegerField(blank=True, verbose_name='incut')),
                ('bend', models.SmallIntegerField(blank=True, verbose_name='bend')),
                ('prod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdm.product')),
            ],
            options={
                'verbose_name': 'Свойства продукции (производство)',
                'verbose_name_plural': 'Свойства продукции (производство)',
                'ordering': ['prod'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='spc',
            field=models.ManyToManyField(through='pdm.Spc', to='pdm.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdm.unit'),
        ),
    ]
