# Generated by Django 3.1.1 on 2020-09-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='cam_file',
            field=models.FileField(blank=True, upload_to='cam_files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='drawing',
            field=models.FileField(blank=True, upload_to='drawings'),
        ),
    ]
