# Generated by Django 3.1.1 on 2020-09-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0003_auto_20200921_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproperties',
            options={'ordering': ['prod'], 'verbose_name': 'Свойства деталей', 'verbose_name_plural': 'Свойства деталей'},
        ),
        migrations.AlterModelOptions(
            name='spc',
            options={'ordering': ['owner', 'member'], 'verbose_name': 'Спецификация', 'verbose_name_plural': 'Спецификации'},
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='property_form',
            field=models.CharField(blank=True, max_length=5, verbose_name='property_form'),
        ),
        migrations.AlterField(
            model_name='productproperties',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='productproperties',
            name='bend',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='bend'),
        ),
        migrations.AlterField(
            model_name='productproperties',
            name='incut',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='incut'),
        ),
        migrations.AlterField(
            model_name='productproperties',
            name='perimeter',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='perimeter'),
        ),
        migrations.AlterField(
            model_name='productproperties',
            name='stocksize',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='stocksize'),
        ),
    ]
