# Generated by Django 3.1.1 on 2020-09-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0004_auto_20200921_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='product',
            name='bend',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='bend'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating',
            field=models.CharField(blank=True, max_length=100, verbose_name='coating'),
        ),
        migrations.AddField(
            model_name='product',
            name='incut',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='incut'),
        ),
        migrations.AddField(
            model_name='product',
            name='perimeter',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='perimeter'),
        ),
        migrations.AddField(
            model_name='product',
            name='stocksize',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='stocksize'),
        ),
        migrations.AddField(
            model_name='product',
            name='treatment',
            field=models.CharField(blank=True, max_length=15, verbose_name='treatment'),
        ),
        migrations.DeleteModel(
            name='ProductProperties',
        ),
    ]
