# Generated by Django 3.1.1 on 2020-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm', '0005_auto_20200922_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='spc',
            name='note',
            field=models.CharField(blank=True, max_length=15, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cam_file',
            field=models.FileField(blank=True, upload_to='pdm/cam_files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='drawing',
            field=models.FileField(blank=True, upload_to='pdm/drawings'),
        ),
    ]
