# Generated by Django 3.1.1 on 2020-09-20 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdm', '0001_initial'),
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=15, unique=True, verbose_name='order_number')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='creation_date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='amount')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='discount_percent')),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='tax_percent')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='total')),
                ('image', models.ImageField(upload_to='orders')),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdm.counterparty')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('goods', models.ManyToManyField(to='good.Good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Состав счета',
                'verbose_name_plural': 'Составы счетов',
                'ordering': ['order'],
            },
        ),
    ]
