# Generated by Django 3.1.1 on 2020-09-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0002_auto_20200921_2156'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.FileField(upload_to='orders'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='goods',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='good.good'),
        ),
    ]
