# Generated by Django 3.1.1 on 2020-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200921_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='discount_percent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.FileField(blank=True, upload_to='orders'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='tax_percent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='total'),
        ),
    ]
