# Generated by Django 3.1.1 on 2020-09-22 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200921_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today, verbose_name='order_date'),
        ),
    ]
